tls_profile:
  client_cert: certs/client-cert.pem
  client_key: certs/client-key.pem
  ca_cert: certs/ca.pem
  server_name: <SERVER_NAME>

# Batching configuration
batch_config:
  max_batch_size: 1000        # Maximum number of records per batch
  max_batch_bytes: 1048576    # Maximum bytes per batch (1MB)
  flush_interval_ms: 1000     # Flush interval in milliseconds
  enable_compression: true    # Enable GZIP compression
  
routes:
  - name: windows
    listen:
      ip: "0.0.0.0"
      port: 9999
      protocol: tcp
    forward:
      host: <BACKEND_SERVICE_IP_OR_HOST>
      port: <BACKEND_SERVICE_PORT>
      tls: true         # Optional; default is true
  - name: linux
    listen:
      ip: "0.0.0.0"
      port: 9998
      protocol: tcp
    forward:
      host: <BACKEND_SERVICE_IP_OR_HOST>
      port: <BACKEND_SERVICE_PORT>
      tls: true